### ISSUE TITLE
Actualizar flimage para nuevo tipo flotante.

### ISSUE THREAD

**Issue by jmm497** [PRIS2/osadia#8]

**Comment by isirnclw** [comment]
\graphicspath{{Capturas/}}
\newcommand{\flimage}[2]
{
    \begin{Captura}
        \centering
        \includegraphics{#1}
        \caption{#2}
        \setlength{\parskip}{3mm}     % !
        \setlength{\parindent}{3mm}   % !
        \frenchspacing
        \sloppy
 \end{Captura}
}
